---
title: "Antarctic geographic placenames"
author: "Ben Raymond, Michael Sumner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{antanym}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Background

General blurb about the names, including the CGA.

# Examples

```{r chunk_name,eval=TRUE,echo=TRUE,message=TRUE,warning=TRUE,tidy=FALSE,cache=TRUE,include=TRUE,dpi=72,fig.width=7,fig.height=7,fig.align="center",results="markup"}

```

```{r message=FALSE,warning=FALSE}
library(antanym)
library(dplyr)
g <- an_read()
```

## Simple leaflet demo
```{r eval=FALSE}
library(leaflet)

## find single name per feature, preferring United Kingdom
##  names where available, and only rows with valid locations
temp <- g %>% an_preferred("United Kingdom") %>% filter(!is.na(longitude) & !is.na(latitude))

## replace NAs with empty strings in narrative
temp$narrative[is.na(temp$narrative)] <- ""

## formatted popup HTML
popup <- sprintf("<h1>%s</h1><p><strong>Country of origin:</strong> %s<br /><strong>Longitude:</strong> %g<br /><strong>Latitude:</strong> %g<br /><a href=\"https://data.aad.gov.au/aadc/gaz/scar/display_name.cfm?gaz_id=%d\">Link to SCAR gazetteer</a></p>",temp$place_name,temp$country_name,temp$longitude,temp$latitude,temp$gaz_id)

m <- leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addMarkers(lng=temp$longitude,lat=temp$latitude,group="placenames",
    clusterOptions = markerClusterOptions(),popup=popup,
    label=temp$place_name,labelOptions=labelOptions(textOnly=TRUE))

## not displayed here
#print(m)
```

```{r eval=FALSE,include=FALSE}
library(mapview)
## only rows with valid locations
idx <- !is.na(g$longitude) & !is.na(g$latitude)

temp <- g[idx,]
coordinates(temp) <- ~longitude+latitude
proj4string(temp) <- CRS("+proj=longlat +ellps=WGS84")

## replace NAs with empty strings
temp$narrative[is.na(temp$narrative)] <- ""
## formatted popup HTML
popup <- sprintf("<h1>%s</h1><p><strong>Country of origin:</strong> %s<br />Longitude %g, latitude %g</p><p>%s</p>",temp$place_name,temp$country_name,temp$longitude,temp$latitude,temp$narrative)

mapview(as(temp,"SpatialPoints"),popup=popupTable(temp,zcol=c("place_name","country_name","narrative")))

label=temp$place_name)

```
